server:
  port: 8760

eureka:
  instance:
    # hostname: chapter4-eureka-client-service
    # 一台主机可以启动多个属于同一服务的服务实例
    instance-id: ${spring.application.name}:${vcap.application.instance-id:${spring.application.instance-id:${random.value}}}

  client:
    # eureka server注册中心的地址，用于client与server进行交流
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-client-server