server:
  port: 8876

spring:
  application:
    name: hystrix-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true