spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - RemoveRequestHeader=Origin
        routes:
        - id: default_path_to_httpbin
        uri: localhost:9090
        order: 10000
        predicates:
        - Path=/**
        filters:
        - AddRequestParameter=foo, bar