server:
  port: 8005

spring:
  application:
    name: gateway-user-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
        instance-id: user-${server.port}
        service-name: gateway-user
